algoritmo "SE_par_ou_impar"
// Função :
// Autor :  @patyfreitasbr
// Data : 05/06/2024
// Seção de Declarações 
var
   numero: inteiro

inicio
// Seção de Comandos 


 escreval ("Digite um numero inteiro: ")
 leia (numero)
      se (numero mod 2 =0) entao

      escreval ("O número é, ", numero , " é PAR")
      senao
      escreval ("O número é, ", numero , " é IMPAR")

      fimSE

fimalgoritmo
